spring:
  application:
    name: easy-property-configuration
  devtools:
    restart:
      enabled: true

app:
  system:
    name: test-app
    version: 2.0.0

  tenants:
      - name: tenant-a
        partners:
          - id: partner-1
            contract:
              - start: 01-01-25
              - end: 30-12-99

          - id: partner-1

          - id: partner-2
            contract:
              - start: 01-01-25
              - end: 31-12-99

      - name: tenant-b
        partners:
          - id: partner-3

          - id: partner-2

        customers:
          - id: customer-1
            subscription: TRUE
            renewal: FALSE
            additional:
              key1: value1
              key2: value2
  metadata:
    key1: value1
    key2: value2

#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,metrics,info
#  endpoint:
#    health:
#      show-details: always
#  metrics:
#    tags:
#      application: ${spring.application.name}
#
#logging:
#  level:
#    root: INFO
#    com.example: DEBUG
#  pattern:
#    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
#  file:
#    name: logs/application.log
#    max-size: 10MB
#
#security:
#  jwt:
#    secret: ${JWT_SECRET}
#    expiration: 86400
#  cors:
#    allowed-origins:
#      - http://localhost:3000
#      - https://example.com
#    allowed-methods:
#      - GET
#      - POST
#      - PUT
#      - DELETE
#
#kafka:
#  bootstrap-servers: localhost:9092
#  consumer:
#    group-id: my-group
#    auto-offset-reset: earliest
#  producer:
#    retries: 3
#    batch-size: 16384
#  topics:
#    user-events: user-events
#    notification: notification-events
#
#redis:
#  host: localhost
#  port: 6379
#  password: ${REDIS_PASSWORD}
#  timeout: 2000
#  database: 0
#  clusters:
#    - host: redis-1
#      port: 6379
#    - host: redis-2
#      port: 6379
#
#email:
#  smtp:
#    host: smtp.gmail.com
#    port: 587
#    username: ${SMTP_USERNAME}
#    password: ${SMTP_PASSWORD}
#    auth: true
#    starttls: true
#  defaults:
#    from: noreply@example.com
#    subject-prefix: "[TEST-APP]"
#
#aws:
#  region: us-east-1
#  s3:
#    bucket: my-application-bucket
#    access-key: ${AWS_ACCESS_KEY}
#    secret-key: ${AWS_SECRET_KEY}
#  sqs:
#    queue-url: https://sqs.us-east-1.amazonaws.com/123456789/my-queue
#  sns:
#    topic-arn: arn:aws:sns:us-east-1:123456789:my-topic
#
#monitoring:
#  enabled: true
#  metrics:
#    jvm: true
#    http: true
#    cache: true
#  alerts:
#    slack-webhook: ${SLACK_WEBHOOK}
#    email-recipients:
#      - admin@example.com
#      - support@example.com
#  tracing:
#    enabled: true
#    sampling-rate: 0.1
#
#feature-flags:
#  new-ui: true
#  beta-features: false
#  maintenance-mode: false
#  rate-limiting:
#    enabled: true
#    requests-per-second: 100