spring:
  application:
    name: easy-property-configuration
  devtools:
    restart:
      enabled: true

app:
  system:
    name: test-app
    version: 2.0.0
  tenants:
      - name: tenant-a
        partners:
          - id: partner-1
          - id: partner-2
      - name: tenant-b
        partners:
          - id: partner-3
          - id: partner-2
